config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :clients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
=begin   has_many :phones, dependent: :destroy, inverse_of: :client
=end
end

app/models/email.rb
=begin class Email < ApplicationRecord
  belongs_to :client
end =end

app/models/phone.rb
=begin class Phone < ApplicationRecord
  belongs_to :client
end
 =end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id]) 
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params) 
    if @client.save
      redirect_to (@client) 
    else 
      render :new
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
		if @client.update(client_params)
			redirect_to @client
		else
			render :edit
		end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy 
    redirect_to clients_path 
  end

  private 

  def client_params
    params.require(:client)
          .permit(:name, :email, :phone, :register_date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_form.html.erb
<% @client.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: @client, local: true do |f| %>
  <div>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name, placeholder: 'Albert Einstein'  %>
  </div>
  <div>
    <%= f.label :email, 'E-mail' %>
    <%= f.text_field :email, placeholder: 'email@gmail.com'  %>
  </div>
  <div>
    <%= f.label :phone, 'Phone number' %>
    <%= f.text_field :phone, placeholder: 'xxx-xxx-xxxx'  %>
  </div>
  <div>
    <%= f.label :register_date, 'Register date' %>
    <%= f.text_field :register_date, placeholder: '2020/08/25'  %>
  </div>
    <%= f.submit "Save" %>
<% end %>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>

<%= render partial: 'form', locals: { client: @client} %>

app/views/clients/index.html.erb
<%= link_to 'Go back', root_path%>

<ol><% @clients.each do |client| %>
  <li><%= link_to client.name, client %></li>
<% end %></ol>

<% if @clients.empty? %>
		<%= 'Ooops...You don\'t have any Client registered yet! But you can do it here:' %>
<% end %>

<p><%= link_to 'Register a new client', new_client_path %></p>

app/views/clients/new.html.erb
<h1>Register a new Client:</h1>

<%= render partial: 'form', locals: { client: @client } %>

app/views/clients/show.html.erb
<%= link_to 'Go back', clients_path%> <br>

<h1><%= @client.name %></h1>

<table border="2px solid black">
  <tr>
    <th><%= Client.human_attribute_name(:email) %></th>
    <th><%= Client.human_attribute_name(:phone) %></th>
    <th><%= Client.human_attribute_name(:register_date) %></th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <tr style="text-align:right">
    <td><%= @client.email %></td>
    <td><%= @client.phone %></td>
    <td><%= @client.register_date %></td>
    <td style="text-align:center"><%= link_to 'Edit', edit_client_path(@client) %></td>
    <td style="text-align:center"><%= link_to 'Delete', client_path(@client), method: :delete, data: { confirm: 'Are you sure you want to delete this Client?' } %></td>
   </tr>
</table>

app/views/home/index.html.erb
<header>
<h1>Client Registration System</h1>
<h2>Welcome to our client registration system</h2>
</header>
<a href="<%= clients_path %>">Clients</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioCustomerx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>